# Generated by Django 6.0.2 on 2026-02-24 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mulk egasi')),
                ('cadastre_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kadastr raqami')),
                ('total_area', models.CharField(blank=True, max_length=50, null=True, verbose_name='Umumiy maydon')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Joylashuv')),
                ('built_year', models.IntegerField(blank=True, null=True, verbose_name='Qurilgan yili')),
                ('purpose', models.CharField(blank=True, choices=[('garov', 'Garov qiymati'), ('soliq', 'Soliq qiymati'), ('nizom_fond', 'Nizom fond qiymati'), ('investitsion', 'Investitsion qiymati'), ('snos', 'Snos va yetkazilgan zarar')], max_length=20, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_valuations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='OLX', max_length=50)),
                ('rooms', models.IntegerField(verbose_name='Xona soni')),
                ('area', models.CharField(max_length=50, verbose_name='Maydon')),
                ('condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Holati')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('date_posted', models.CharField(blank=True, max_length=100, null=True)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogs', to='real_estate.realestatevaluation')),
            ],
        ),
    ]
