# Generated by Django 6.0.2 on 2026-03-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realestateanalog',
            options={'verbose_name': "Ko'chmas mulk analogi", 'verbose_name_plural': "Ko'chmas mulk analoglari"},
        ),
        migrations.AlterModelOptions(
            name='realestatevaluation',
            options={'verbose_name': "Ko'chmas mulk baholash", 'verbose_name_plural': "Ko'chmas mulk baholashlari"},
        ),
    ]
