# Generated by Django 6.0.2 on 2026-04-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_realestatevaluation_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatevaluation',
            name='calculation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='realestatevaluation',
            name='confirmed_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='realestatevaluation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='realestatevaluation',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Tasdiq kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='draft', max_length=20),
        ),
    ]
