# Generated by Django 6.0.2 on 2026-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_realestatevaluation_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatevaluation',
            name='agreement_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='realestatevaluation',
            name='agreement_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realestatevaluation',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realestatevaluation',
            name='passport_given_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestatevaluation',
            name='passport_given_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='realestatevaluation',
            name='passport_jshshir',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='realestatevaluation',
            name='passport_serial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='realestatevaluation',
            name='passport_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='realestatevaluation',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
