# Generated by Django 6.0.2 on 2026-02-24 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='F.I.Sh')),
                ('passport_serial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasport seriya va raqami')),
                ('car_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aftomobil rusumi')),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Davlat raqami')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Ishlab chiqarilgan yili')),
                ('vin_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='VIN kod')),
                ('engine_capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dvigatel hajmi')),
                ('method', models.CharField(blank=True, choices=[('qiyosiy', 'Qiyosiy yondashuv'), ('xarajat', 'Xarajat yondashuvi'), ('daromad', 'Daromad yondashuvi')], max_length=20, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_valuations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='OLX', max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('engine_capacity', models.CharField(max_length=50)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('date_posted', models.CharField(blank=True, max_length=100, null=True)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analogs', to='vehicles.vehiclevaluation')),
            ],
        ),
    ]
