# Generated by Django 6.0.2 on 2026-02-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='body_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kuzov asosi raqami'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rangi'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='empty_weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yuksiz vazni'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dvigatel raqami'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Yoqilg'i turi"),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='full_weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="To'la vazni"),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='passport_given_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kim tomonidan berilgan'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='passport_given_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Berilgan sanasi'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='passport_jshshir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='JShShIR'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='seats_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="O'rindiqlar soni"),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='tech_passport_serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guvohnoma seriyasi va raqami'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transport turi'),
        ),
        migrations.AlterField(
            model_name='vehiclevaluation',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Avtomobil rusumi'),
        ),
    ]
