# Generated by Django 6.0.2 on 2026-02-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclevaluation_body_number_vehiclevaluation_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleanalog',
            name='price_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
