# Generated by Django 6.0.2 on 2026-02-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicleanalog_price_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='mileage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yurgan masofasi'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ro'yxatdan o'tkazish raqami (Guvohnoma raqami)"),
        ),
    ]
