# Generated by Django 6.0.2 on 2026-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehiclevaluation_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='agreement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Shartnoma sanasi'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='agreement_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shartnoma raqami'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='valuation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Baholash sanasi'),
        ),
    ]
