# Generated by Django 6.0.2 on 2026-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehiclevaluation_agreement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='engine_horsepower',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dvigatel quvvati (ot kuchi)'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='initial_balance_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dastlabki balans qiymati'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='residual_balance_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Balans qoldiq qiymati'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='technical_condition',
            field=models.CharField(blank=True, default='Qoniqarli', max_length=50, null=True, verbose_name='Texnik holati'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='top_speed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Maksimal tezlik'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='transmission_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yurish qutisi (KPP)'),
        ),
    ]
