# Generated by Django 6.0.2 on 2026-02-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehiclevaluation_engine_horsepower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclevaluation',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='vehiclevaluation',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='vehicleanalog',
            name='adjusted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicleanalog',
            name='wear_adjustment',
            field=models.FloatField(blank=True, null=True, verbose_name='Eskirishga tuzatish'),
        ),
        migrations.AddField(
            model_name='vehicleanalog',
            name='wear_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Jismoniy eskirish %'),
        ),
        migrations.AddField(
            model_name='vehicleanalog',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Vazni (Koeffisiyent)'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='has_corrosion',
            field=models.BooleanField(default=False, verbose_name='Kuzovda korroziya'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='has_creaking',
            field=models.BooleanField(default=False, verbose_name="Eshiklar/kapot g'irchillashi"),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='has_faded_paint',
            field=models.BooleanField(default=False, verbose_name='Rang hiralashishi'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='has_insulation_issue',
            field=models.BooleanField(default=False, verbose_name='Izolyasiya buzilishi'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='has_stains',
            field=models.BooleanField(default=False, verbose_name="Dog'lar"),
        ),
    ]
