# Generated by Django 6.0.2 on 2026-02-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_remove_vehiclevaluation_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='act_wear_percent',
            field=models.FloatField(default=0.0, verbose_name="Dalolatnoma bo'yicha eskirish (%)"),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='aggregate_wear_percent',
            field=models.FloatField(default=0.0, verbose_name='Jamlangan eskirish (%)'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='formula_wear_percent',
            field=models.FloatField(default=0.0, verbose_name="Formula bo'yicha eskirish (%)"),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='replacement_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tiklanish qiymati (USD)'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='scale_wear_percent',
            field=models.FloatField(default=0.0, verbose_name="Shkala bo'yicha eskirish (%)"),
        ),
    ]
