# Generated by Django 6.0.2 on 2026-02-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehiclevaluation_act_wear_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='mileage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Bosib o'tgan masofasi"),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ro'yxatdan o'tkazish raqami"),
        ),
    ]
