# Generated by Django 6.0.2 on 2026-02-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehiclevaluation_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='passport_type',
            field=models.CharField(blank=True, default="O'zbekiston Respublikasi Fuqarosining ID-kartasi", max_length=100, null=True, verbose_name='Hujjat turi'),
        ),
    ]
