# Generated by Django 6.0.2 on 2026-02-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehiclevaluation_passport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleanalog',
            name='body_type',
            field=models.CharField(blank=True, default='Sedan', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicleanalog',
            name='color',
            field=models.CharField(blank=True, default='Oq', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicleanalog',
            name='has_corrosion',
            field=models.CharField(blank=True, default='mavjud', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicleanalog',
            name='has_creaking',
            field=models.CharField(blank=True, default='ma’lumot yo‘q', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicleanalog',
            name='has_faded_paint',
            field=models.CharField(blank=True, default='mavjud', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicleanalog',
            name='has_insulation_issue',
            field=models.CharField(blank=True, default='ma’lumot yo‘q', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicleanalog',
            name='has_stains',
            field=models.CharField(blank=True, default='mavjud', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicleanalog',
            name='transmission',
            field=models.CharField(blank=True, default='Mexanika', max_length=50, null=True),
        ),
    ]
