# Generated by Django 6.0.2 on 2026-02-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_vehicleanalog_body_type_vehicleanalog_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='tech_passport_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tex-pasport egasi'),
        ),
    ]
