# Generated by Django 6.0.2 on 2026-03-03 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_vehiclevaluation_tech_passport_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleanalog',
            options={'verbose_name': 'Avtomobil analogi', 'verbose_name_plural': 'Avtomobil analoglari'},
        ),
        migrations.AlterModelOptions(
            name='vehiclevaluation',
            options={'verbose_name': 'Avtomobil baholash', 'verbose_name_plural': 'Avtomobil baholashlari'},
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_valuations', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan Baholovchi'),
        ),
        migrations.AlterField(
            model_name='vehiclevaluation',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Tasdiqlash kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='draft', max_length=20),
        ),
    ]
