# Generated by Django 6.0.2 on 2026-03-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_vehicleanalog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='passport_birth_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Tug'ilgan sanasi"),
        ),
    ]
