# Generated by Django 6.0.2 on 2026-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_vehiclevaluation_passport_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/vehicles/', verbose_name="To'lov cheki"),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='Baholash narxi'),
        ),
        migrations.AlterField(
            model_name='vehiclevaluation',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('payment_pending', 'To`lov kutilmoqda'), ('verifying', 'To`lov tekshirilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='draft', max_length=20),
        ),
    ]
