# Generated by Django 6.0.2 on 2026-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_vehiclevaluation_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='report_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hisobot raqami'),
        ),
    ]
