# Generated by Django 6.0.2 on 2026-05-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_vehiclevaluation_report_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.IntegerField(default=1)),
                ('create_time', models.BigIntegerField()),
                ('perform_time', models.BigIntegerField(blank=True, null=True)),
                ('cancel_time', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payme_transactions', to='vehicles.vehiclevaluation')),
            ],
            options={
                'verbose_name': 'Payme tranzaksiyasi',
                'verbose_name_plural': 'Payme tranzaksiyalari',
            },
        ),
    ]
