# Generated by Django 6.0.2 on 2026-06-04 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_paymetransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='OLX', max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('engine_capacity', models.CharField(max_length=50)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_string', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_analogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global analog',
                'verbose_name_plural': 'Global analoglar',
            },
        ),
    ]
