# Generated by Django 6.0.2 on 2026-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_globalanalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Sozlama kaliti')),
                ('value', models.TextField(verbose_name='Sozlama qiymati')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan sana')),
            ],
            options={
                'verbose_name': 'Tizim sozlamasi',
                'verbose_name_plural': 'Tizim sozlamalari',
            },
        ),
    ]
