# Generated by Django 6.0.2 on 2026-07-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevaluation',
            name='client_company_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hisob raqami'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='client_company_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kompaniya manzili'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='client_company_bank',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank nomi'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='client_company_inn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='INN'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='client_company_mfo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MFO'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='client_company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kompaniya nomi'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='client_company_oked',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OKED'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='client_type',
            field=models.CharField(choices=[('physical', 'Jismoniy shaxs'), ('legal', 'Yuridik shaxs')], default='physical', max_length=20, verbose_name='Buyurtmachi turi'),
        ),
        migrations.AddField(
            model_name='vehiclevaluation',
            name='mulk_egasi_bir_xil',
            field=models.BooleanField(default=True, verbose_name='Mulk egasi buyurtmachi bilan bir xilmi'),
        ),
    ]
