# Generated by Django 6.0.2 on 2026-05-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=100, unique=True)),
                ('response_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=20)),
                ('region', models.CharField(default='Barchasi', max_length=100)),
                ('avg_price', models.FloatField(default=0)),
                ('listings_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'category', 'region')},
            },
        ),
        migrations.CreateModel(
            name='MarketStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vehicle', 'Vehicle'), ('real_estate', 'Real Estate')], max_length=20)),
                ('item_name', models.CharField(max_length=100)),
                ('avg_price', models.FloatField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('trend', models.CharField(default='+0.0%', max_length=20)),
                ('region', models.CharField(default='Barchasi', max_length=100)),
                ('scrape_source', models.CharField(default='olx', help_text='olx, avtoelon, combined', max_length=50)),
                ('data_json', models.TextField(default='{}', help_text='Raw scraped listings as JSON')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('category', 'item_name', 'region', 'scrape_source')},
            },
        ),
    ]
