# Generated by Django 6.0.2 on 2026-04-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kitob nomi')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Muallif')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('file', models.FileField(upload_to='books/files/', verbose_name='Fayl (PDF/Docx)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='Muqova rasmi')),
                ('category', models.CharField(choices=[('real_estate', "Ko'chmas mulk"), ('vehicles', 'Transport vositalari'), ('legal', 'Qonunchilik'), ('methodology', 'Metodologiya'), ('other', 'Boshqa')], default='other', max_length=50, verbose_name='Kategoriya')),
                ('is_indexed', models.BooleanField(default=False, verbose_name='Indekslangan')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
