# Generated by Django 6.0.2 on 2026-03-03 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_appraiser',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'appraiser'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan Ustoz Baholovchi'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon rqam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('appraiser', 'Baholovchi'), ('assistant', 'Yordamchi Baholovchi')], default='assistant', max_length=20),
        ),
    ]
