# Generated by Django 6.0.2 on 2026-05-04 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_assigned_appraiser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_appraiser',
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan yaratilgan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin (Egasi)'), ('admin', 'Yordamchi Admin'), ('user', 'Foydalanuvchi')], default='user', max_length=20),
        ),
    ]
