# Generated by Django 6.0.2 on 2026-06-04 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_assigned_appraiser_user_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Firma nomi')),
                ('stir', models.CharField(max_length=20, verbose_name='STIR raqami (INN)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Firma Logotipi')),
                ('seal', models.ImageField(blank=True, null=True, upload_to='company_seals/', verbose_name='Firma Muhri (Pechat)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sertifikat/Litsenziya raqami'),
        ),
        migrations.AddField(
            model_name='user',
            name='pinfl',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PINFL'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.company', verbose_name='Qaysi firmaga tegishli'),
        ),
    ]
