# Generated by Django 6.0.2 on 2026-06-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_user_license_number_user_pinfl_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='user_signatures/', verbose_name='Foydalanuvchi Imzosi'),
        ),
    ]
